#sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "cakim21@naver.com"
  - git config --global user.name "Jakezo"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "drsss6SyPzlwrNo3rg6bFeE3l8gK3WJ8xpEKzz0qFVdML+w5qfDqlMJVusZORahTPtrNsJQx7OzDqEh1QX6bLBL1CPQTEQ7zUGdk7b9WQ6kOZUv7EACpk66K2WjrXuDcv0W+a7HPcrz2cPipxLbJyV1Kt3d
             RRS2IXWK3y7h7l3bA/T3mBaEJmsYlu05eEx6hDdOKPivtYjxi/LqcNU1Mi0KQqoo9wpjLoqTQiab393kumJkr01nKAuXp2vLJIpJlBzVw8cMTfC2t7Pln0UuDjxRspt1ZqHlnCJkNVs/shNawq2FfvNCetLto71TOi0atS
             +YjC6xd/kH47K5ntq2kWlvNy2bVURsK+VBEW9T+fM8ZLegZEcyJVV1I3/PMZJVcyFz4ZLumRHaHpncRjHA2jFdLXe3XjjusW41HkeBya4BxGLSfYlv9FZDA/iflrz444jDqAxGe10KeRzf9Ibx3/0Iwr58X4i0Cj9lhR7B
             /Eh7KmAhxdY4PENFRezHW78sNyzdIt6UqA2h4eAYuiuJsL/GrkEOHfLyUelpnU1Wqx9FTR6GXEMMpEzu9RppOrydD4WdVClzWOVKpJ+ox9B5jNHvjRGwh+SoKrx1q9hjMezvjz33YTXda3T9KeiHzbbyjn3P/nOIexEwnW
             iuOukY8ZPERIEA7E2Zpn5tWhZimxtU="
branches:
  only:
    - master