sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "cakim21@naver.com"git submodule add https://github.com/Jakezo/jakezo.github.io.git output
  - git config --global user.name "Jakezo"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "TPcjB+P4r+z5TRm/wT63ivp8PMvMf/e8UbuSliU4P67Xec9EpM06rXVq+O0s1Rnp5GyInu/fBtwm8W2ZS/fSfvQ50VUUz0dJ/CAOvIpQdL0qBYBXUkPH//cU8/68OiJ1FPZPzHFcCOJiF7KuZH5UmGEoc6f
            Hyt/UWxlDckebZloZM8p1LGc95fAEirTjYkVkXYyOUCyCYQuMoXhtf81DlNLZAo/eFI3gldjFmtcFfR2dMxBu7LtgIagDeFxzpo2zsoPtXQO64dg2Dy4r5fY1SQwMCclDpwqgWSd5RIpr08uj25O9uLhkPfNmMPsUMiPYF
            PRfgGsIogEBtwtoOHnTAmiJIYoWi7TI8c/qpVopjN99wHyUHsfRkDfVqeU12e9bhDTbP7A0GoajSLSThzLYTT5lm61om5WkQfCZP+CdhYaCzl86bx4RNSEin+2y1JNbvpOExgLa0A6rBfiWH6XzR8stFTs/r/yIOIO8oSK
            YuJ47u6ozy1ST97el8fSUtDIeEP2WSsUNABHt/MXrip2YS5VOniH4CMAQ+HwZ7p6ZNGXit8cwiJ3ZZMtMblm35mxNeuj6tY6DXBT8vqa/G3XlFP1v/TpcGggNoC5sT4yHmhIYb+Z2Yn2D+aToFQD1EKl65JrtOZSFZ6CG7
            4AIvRbDA+C+ba/YBfVk5ORov9lhVlM="

branches:
  only:
    - master